#!/bin/sh
  # eleven patchGoMod /go/app/go.mod "golang.org/x/net|v0.23.0|GHSA-4v7x-pqxf-cx7m"

  GO_MOD="${1}"
  shift
  if [ -f ${GO_MOD} ]; then
    for GoIssue in "$@"; do
      DETAILS=$(echo "${GoIssue}" | tr "|" "\n")
      MOD=$(echo "${DETAILS}" | sed '1!d')
      FIX=$(echo "${DETAILS}" | sed '2!d')
      ISSUE=$(echo "${DETAILS}" | sed '3!d')
      sed -i 's#'${MOD}' .\+[0-9]\+#'${MOD}' '${FIX}'#g' ${GO_MOD}
      if [ $? ]; then
        eleven log debug "fixing ${ISSUE} for module ${MOD} in ${GO_MOD}"
      fi
    done
  fi