#!/bin/sh
  # returns a random string
  # eleven randomString
  # eleven randomString 32 (max length)

  if [ -z "${1}" ]; then
    MAX=64
  else
    MAX=${1}
  fi
  echo "$(echo "${RANDOM}$(date)${RANDOM}" | sha512sum | cut -d' ' -f1 | awk '{print substr($0, 0, '${MAX}')}')"